name: "이슈 생성"
description: "Repo에 이슈를 생성하며, 자동으로 브랜치를 생성합니다."
labels: [feat]
title: "이슈 이름을 작성해주세요"
body:
  - type: dropdown
    id: branch_type
    attributes:
      label: "Branch Type"
      options:
        - feat
        - fix
        - refactor
        - chore
        - hotfix
        - docs

  - type: input
    id: description
    attributes:
      label: "📝 Description"
    validations:
      required: false

  - type: textarea
    id: tasks
    attributes:
      label: "✅ Tasks"
      description: "해당 이슈에 대해 필요한 작업목록을 작성해주세요"
    validations:
      required: false
