name: "이슈 생성"
description: "이슈를 생성하며, 자동으로 브랜치를 생성합니다."
title: "이슈 이름을 작성해주세요"
body:
  - type: dropdown
    id: branch_type
    attributes:
      label: "Branch Type"
      options:
        - feat
        - fix
        - refactor
        - chore
        - hotfix
        - docs

  - type: input
    id: description
    attributes:
      label: "📝 Description"
    validations:
      required: false
